-- ----------------------------------------------------------------
-- 🛑 DO NOT EDIT THIS FILE!
-- Regenerated by: edgespark pull schema --db
--
-- To modify your database schema (multiple statements in one command):
--   edgespark db sql "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);
--     CREATE TABLE posts (id INTEGER PRIMARY KEY, user_id INTEGER REFERENCES users(id), created_at INTEGER);
--     CREATE INDEX idx_posts_created ON posts(created_at)"
--
-- To query your database:
--   edgespark db sql "SELECT * FROM posts; SELECT COUNT(*) FROM users"
-- ----------------------------------------------------------------

-- TABLES

CREATE TABLE characters (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  image TEXT,
  thumbnail TEXT,
  style_id TEXT,
  description TEXT,
  prompt TEXT,
  gender TEXT,
  mbti TEXT,
  personality_tags TEXT,
  catchphrase TEXT,
  story TEXT,
  is_public INTEGER DEFAULT 0,
  likes INTEGER DEFAULT 0,
  collects INTEGER DEFAULT 0,
  created_at INTEGER DEFAULT (unixepoch())
);

CREATE TABLE chat_messages (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  oc1_id INTEGER NOT NULL,
  oc2_id INTEGER NOT NULL,
  sender_id INTEGER NOT NULL,
  content TEXT NOT NULL,
  timestamp INTEGER DEFAULT (unixepoch())
);

CREATE TABLE `es_system__auth_user` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`email` text NOT NULL,
	`email_verified` integer DEFAULT false NOT NULL,
	`image` text,
	`created_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`updated_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`is_anonymous` integer DEFAULT false,
	`__internal_a` text,
	`banned` integer DEFAULT false,
	`ban_reason` text,
	`ban_expires` integer,
	`last_login_at` integer
);

CREATE TABLE interaction_history (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id TEXT NOT NULL,
  character_ids TEXT NOT NULL,
  character_names TEXT NOT NULL,
  scenario TEXT NOT NULL,
  dialogues TEXT NOT NULL,
  created_at INTEGER DEFAULT (unixepoch())
);

CREATE TABLE locations (
  user_id INTEGER PRIMARY KEY,
  oc_id INTEGER,
  lat REAL,
  lng REAL,
  updated_at INTEGER DEFAULT (unixepoch())
);

CREATE TABLE oc_conversations (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  oc1_id INTEGER NOT NULL,
  oc2_id INTEGER NOT NULL,
  scenario TEXT,
  summary TEXT,
  dialogue_json TEXT NOT NULL,
  is_auto_generated INTEGER DEFAULT 0,
  created_at INTEGER DEFAULT (unixepoch())
);

CREATE TABLE oc_relationships (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  oc_id INTEGER NOT NULL,
  target_oc_id INTEGER NOT NULL,
  relationship_type TEXT NOT NULL DEFAULT 'friend',
  affinity_score INTEGER DEFAULT 50,
  interaction_count INTEGER DEFAULT 0,
  last_interaction_at INTEGER,
  created_at INTEGER DEFAULT (unixepoch()),
  UNIQUE(oc_id, target_oc_id)
);

CREATE TABLE oc_social_feeds (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  oc_id INTEGER NOT NULL,
  feed_type TEXT NOT NULL DEFAULT 'status',
  content TEXT NOT NULL,
  target_oc_id INTEGER,
  likes INTEGER DEFAULT 0,
  created_at INTEGER DEFAULT (unixepoch())
);

CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT,
  nickname TEXT,
  avatar TEXT,
  bio TEXT,
  created_at INTEGER DEFAULT (unixepoch())
);

-- INDEXS

CREATE UNIQUE INDEX `es_system__auth_user_email_unique` ON `es_system__auth_user` (`email`);

CREATE INDEX idx_characters_user_id ON characters(user_id);

CREATE INDEX idx_chat_messages_oc1_oc2 ON chat_messages(oc1_id, oc2_id);

CREATE INDEX idx_interaction_history_user ON interaction_history(user_id);

CREATE INDEX idx_oc_conversations_ocs ON oc_conversations(oc1_id, oc2_id);

CREATE INDEX idx_oc_relationships_oc ON oc_relationships(oc_id);

CREATE INDEX idx_oc_relationships_target ON oc_relationships(target_oc_id);

CREATE INDEX idx_oc_social_feeds_oc ON oc_social_feeds(oc_id);
