// ----------------------------------------------------------------
// 🛑 AUTO-GENERATED FILE - DO NOT EDIT!
// Regenerated by: edgespark pull schema --db
//
// To modify your database schema (multiple statements in one command):
//   edgespark db sql "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);
//     CREATE TABLE posts (id INTEGER PRIMARY KEY, user_id INTEGER REFERENCES users(id), created_at INTEGER);
//     CREATE INDEX idx_posts_created ON posts(created_at)"
//
// To query your database:
//   edgespark db sql "SELECT * FROM posts; SELECT COUNT(*) FROM users"
// ----------------------------------------------------------------

import { sqliteTable, AnySQLiteColumn, uniqueIndex, text, integer, index, real } from "drizzle-orm/sqlite-core"
  import { sql } from "drizzle-orm"

export const esSystemAuthUser = sqliteTable("es_system__auth_user", {
	id: text().primaryKey().notNull(),
	name: text().notNull(),
	email: text().notNull(),
	emailVerified: integer("email_verified").default(0).notNull(),
	image: text(),
	createdAt: integer("created_at").default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`).notNull(),
	updatedAt: integer("updated_at").default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`).notNull(),
	isAnonymous: integer("is_anonymous").default(0),
	internalA: text("__internal_a"),
	banned: integer().default(0),
	banReason: text("ban_reason"),
	banExpires: integer("ban_expires"),
	lastLoginAt: integer("last_login_at"),
},
(table) => [
	uniqueIndex("es_system__auth_user_email_unique").on(table.email),
]);

export const users = sqliteTable("users", {
	id: integer().primaryKey({ autoIncrement: true }),
	email: text().notNull(),
	passwordHash: text("password_hash"),
	nickname: text(),
	avatar: text(),
	bio: text(),
	createdAt: integer("created_at").default(sql`(unixepoch())`),
});

export const characters = sqliteTable("characters", {
	id: integer().primaryKey({ autoIncrement: true }),
	userId: integer("user_id").notNull(),
	name: text().notNull(),
	image: text(),
	thumbnail: text(),
	styleId: text("style_id"),
	description: text(),
	prompt: text(),
	gender: text(),
	mbti: text(),
	personalityTags: text("personality_tags"),
	catchphrase: text(),
	story: text(),
	isPublic: integer("is_public").default(0),
	likes: integer().default(0),
	collects: integer().default(0),
	createdAt: integer("created_at").default(sql`(unixepoch())`),
},
(table) => [
	index("idx_characters_user_id").on(table.userId),
]);

export const chatMessages = sqliteTable("chat_messages", {
	id: integer().primaryKey({ autoIncrement: true }),
	oc1Id: integer("oc1_id").notNull(),
	oc2Id: integer("oc2_id").notNull(),
	senderId: integer("sender_id").notNull(),
	content: text().notNull(),
	timestamp: integer().default(sql`(unixepoch())`),
},
(table) => [
	index("idx_chat_messages_oc1_oc2").on(table.oc1Id, table.oc2Id),
]);

export const locations = sqliteTable("locations", {
	userId: integer("user_id").primaryKey(),
	ocId: integer("oc_id"),
	lat: real(),
	lng: real(),
	updatedAt: integer("updated_at").default(sql`(unixepoch())`),
});

export const interactionHistory = sqliteTable("interaction_history", {
	id: integer().primaryKey({ autoIncrement: true }),
	userId: text("user_id").notNull(),
	characterIds: text("character_ids").notNull(),
	characterNames: text("character_names").notNull(),
	scenario: text().notNull(),
	dialogues: text().notNull(),
	createdAt: integer("created_at").default(sql`(unixepoch())`),
},
(table) => [
	index("idx_interaction_history_user").on(table.userId),
]);

export const ocRelationships = sqliteTable("oc_relationships", {
	id: integer().primaryKey({ autoIncrement: true }),
	ocId: integer("oc_id").notNull(),
	targetOcId: integer("target_oc_id").notNull(),
	relationshipType: text("relationship_type").default("friend").notNull(),
	affinityScore: integer("affinity_score").default(50),
	interactionCount: integer("interaction_count").default(0),
	lastInteractionAt: integer("last_interaction_at"),
	createdAt: integer("created_at").default(sql`(unixepoch())`),
},
(table) => [
	index("idx_oc_relationships_target").on(table.targetOcId),
	index("idx_oc_relationships_oc").on(table.ocId),
]);

export const ocSocialFeeds = sqliteTable("oc_social_feeds", {
	id: integer().primaryKey({ autoIncrement: true }),
	ocId: integer("oc_id").notNull(),
	feedType: text("feed_type").default("status").notNull(),
	content: text().notNull(),
	targetOcId: integer("target_oc_id"),
	likes: integer().default(0),
	createdAt: integer("created_at").default(sql`(unixepoch())`),
},
(table) => [
	index("idx_oc_social_feeds_oc").on(table.ocId),
]);

export const ocConversations = sqliteTable("oc_conversations", {
	id: integer().primaryKey({ autoIncrement: true }),
	oc1Id: integer("oc1_id").notNull(),
	oc2Id: integer("oc2_id").notNull(),
	scenario: text(),
	summary: text(),
	dialogueJson: text("dialogue_json").notNull(),
	isAutoGenerated: integer("is_auto_generated").default(0),
	createdAt: integer("created_at").default(sql`(unixepoch())`),
},
(table) => [
	index("idx_oc_conversations_ocs").on(table.oc1Id, table.oc2Id),
]);

