import {
  pgTable,
  uniqueIndex,
  text,
  integer,
  index,
  doublePrecision,
  serial,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

export const users = pgTable("users", {
  id: serial().primaryKey(),
  email: text().notNull(),
  passwordHash: text("password_hash"),
  nickname: text(),
  avatar: text(),
  bio: text(),
  createdAt: integer("created_at").default(
    sql`extract(epoch from now())::integer`
  ),
});

export const characters = pgTable(
  "characters",
  {
    id: serial().primaryKey(),
    userId: integer("user_id").notNull(),
    name: text().notNull(),
    image: text(),
    thumbnail: text(),
    styleId: text("style_id"),
    description: text(),
    prompt: text(),
    gender: text(),
    mbti: text(),
    personalityTags: text("personality_tags"),
    catchphrase: text(),
    story: text(),
    isPublic: integer("is_public").default(0),
    likes: integer().default(0),
    collects: integer().default(0),
    createdAt: integer("created_at").default(
      sql`extract(epoch from now())::integer`
    ),
  },
  (table) => [index("idx_characters_user_id").on(table.userId)]
);

export const chatMessages = pgTable(
  "chat_messages",
  {
    id: serial().primaryKey(),
    oc1Id: integer("oc1_id").notNull(),
    oc2Id: integer("oc2_id").notNull(),
    senderId: integer("sender_id").notNull(),
    content: text().notNull(),
    timestamp: integer().default(
      sql`extract(epoch from now())::integer`
    ),
  },
  (table) => [index("idx_chat_messages_oc1_oc2").on(table.oc1Id, table.oc2Id)]
);

export const locations = pgTable("locations", {
  userId: integer("user_id").primaryKey(),
  ocId: integer("oc_id"),
  lat: doublePrecision(),
  lng: doublePrecision(),
  updatedAt: integer("updated_at").default(
    sql`extract(epoch from now())::integer`
  ),
});

export const interactionHistory = pgTable(
  "interaction_history",
  {
    id: serial().primaryKey(),
    userId: text("user_id").notNull(),
    characterIds: text("character_ids").notNull(),
    characterNames: text("character_names").notNull(),
    scenario: text().notNull(),
    dialogues: text().notNull(),
    createdAt: integer("created_at").default(
      sql`extract(epoch from now())::integer`
    ),
  },
  (table) => [index("idx_interaction_history_user").on(table.userId)]
);

export const ocRelationships = pgTable(
  "oc_relationships",
  {
    id: serial().primaryKey(),
    ocId: integer("oc_id").notNull(),
    targetOcId: integer("target_oc_id").notNull(),
    relationshipType: text("relationship_type").default("friend").notNull(),
    affinityScore: integer("affinity_score").default(50),
    interactionCount: integer("interaction_count").default(0),
    lastInteractionAt: integer("last_interaction_at"),
    createdAt: integer("created_at").default(
      sql`extract(epoch from now())::integer`
    ),
  },
  (table) => [
    index("idx_oc_relationships_target").on(table.targetOcId),
    index("idx_oc_relationships_oc").on(table.ocId),
    uniqueIndex("idx_oc_relationships_unique").on(
      table.ocId,
      table.targetOcId
    ),
  ]
);

export const ocSocialFeeds = pgTable(
  "oc_social_feeds",
  {
    id: serial().primaryKey(),
    ocId: integer("oc_id").notNull(),
    feedType: text("feed_type").default("status").notNull(),
    content: text().notNull(),
    targetOcId: integer("target_oc_id"),
    likes: integer().default(0),
    createdAt: integer("created_at").default(
      sql`extract(epoch from now())::integer`
    ),
  },
  (table) => [index("idx_oc_social_feeds_oc").on(table.ocId)]
);

export const ocConversations = pgTable(
  "oc_conversations",
  {
    id: serial().primaryKey(),
    oc1Id: integer("oc1_id").notNull(),
    oc2Id: integer("oc2_id").notNull(),
    scenario: text(),
    summary: text(),
    dialogueJson: text("dialogue_json").notNull(),
    isAutoGenerated: integer("is_auto_generated").default(0),
    createdAt: integer("created_at").default(
      sql`extract(epoch from now())::integer`
    ),
  },
  (table) => [
    index("idx_oc_conversations_ocs").on(table.oc1Id, table.oc2Id),
  ]
);
